version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - GLOBAL_SERVER_URL=${GLOBAL_SERVER_URL}

volumes:
  mongo-data:
