import { ReactQueryClientProvider } from "@/components/react-query-client-provider";
import { NextAuthProvider } from "@/components/session-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { WalletProviderWrapper } from "@/components/wallet-provider-wrapper";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "GX Credentials",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <ReactQueryClientProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <WalletProviderWrapper>
              <main>{children}</main>
              <Toaster />
            </WalletProviderWrapper>
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  </ReactQueryClientProvider>
);

export default RootLayout;
