name: Ligo Compile

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:
  ligo:
    runs-on: ligolang/ligo:1.9.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Compile contract
        run: ligo compile contract ./GXCRegistry.jsligo -m GXCRegistry -o gxcregistry.tz
        working-directory: tezos
