name: Ligo Compile

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:
  ligo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Run build
        uses: marigold-dev/ligo-action@v1.0.0
        with:
          ligo_version: 1.3.0
          command: compile contract ./GXCRegistry.jsligo -m GXCRegistry -o gxcregistry.tz
          working_directory: tezos
