name: Prettier Formatting

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier for frontend
        run: prettier --write "**/*.{js,ts,tsx,md}"
        working-directory: frontend

      - name: Run Prettier for backend
        run: prettier --write "**/*.{js,ts,tsx,md}"
        working-directory: backend
